name = "ValueShapes"
uuid = "136a8f8c-c49b-4edb-8b98-f3d64d48be8f"
version = "0.6.1"

[deps]
ArraysOfArrays = "65a8f2f4-9b39-5baf-92e2-a9cc46fdf018"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ElasticArrays = "fdbdab4c-e67f-52f5-8c3f-e7b388dad3d4"
EmpiricalDistributions = "0bbb1fad-0f24-45fe-94a4-415852c5cc3b"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
TypedTables = "9d95f2ec-7b3d-5a63-8d20-e2491e220bb9"

[compat]
ArraysOfArrays = "0.4"
Distributions = "0.21, 0.22"
ElasticArrays = "1.0"
EmpiricalDistributions = "0.1"
FillArrays = "0.7, 0.8"
IntervalSets = "0.3, 0.4"
StatsBase = "0.32"
Tables = "0.2"
TypedTables = "1.2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
